<?xml version="1.0" encoding="utf-8"?><Database Name="mastercafedb" Class="DataContext_mastercafe" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\MASTERCAFE;Initial Catalog=mastercafedb;User ID=sa" SettingsObjectName="Server.Properties.Settings" SettingsPropertyName="mastercafedbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ban" Member="bans">
    <Type Name="ban">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="word" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.timecode" Member="timecodes">
    <Type Name="timecode">
      <Column Name="code" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="money" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ot" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="timecode_client" Member="clients" ThisKey="code" OtherKey="tc" Type="client" />
      <Association Name="timecode_employee_timecode" Member="employee_timecodes" ThisKey="code" OtherKey="timecode_code" Type="employee_timecode" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="category_item" Member="items" ThisKey="id" OtherKey="category_id" Type="item" />
    </Type>
  </Table>
  <Table Name="dbo.client" Member="clients">
    <Type Name="client">
      <Column Name="name" Type="System.String" DbType="VarChar(256) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ip" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mac" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="group_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="member_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="usedminute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="remainminute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="start" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="app" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tc" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ht" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="wei" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="client_employee_hour" Member="employee_hours" ThisKey="name" OtherKey="client_name" Type="employee_hour" />
      <Association Name="client_reserve" Member="reserves" ThisKey="name" OtherKey="client_name" Type="reserve" />
      <Association Name="timecode_client" Member="timecode" ThisKey="tc" OtherKey="code" Type="timecode" IsForeignKey="true" />
      <Association Name="group_client" Member="group" ThisKey="group_id" OtherKey="id" Type="group" IsForeignKey="true" />
      <Association Name="hourtemplate_client" Member="hourtemplate" ThisKey="ht" OtherKey="id" Type="hourtemplate" IsForeignKey="true" />
      <Association Name="member_client" Member="member" ThisKey="member_name" OtherKey="name" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.config" Member="configs">
    <Type Name="config">
      <Column Name="org_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="org_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="org_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="org_phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="newmember_price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="newmember_stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="close_hour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="alert_minute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="alert_message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="idle_minute" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.employee" Member="employees">
    <Type Name="employee">
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isadmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="employee_employee_hour" Member="employee_hours" ThisKey="name" OtherKey="employee_name" Type="employee_hour" />
      <Association Name="employee_employee_member" Member="employee_members" ThisKey="name" OtherKey="employee_name" Type="employee_member" />
      <Association Name="employee_employee_sale" Member="employee_sales" ThisKey="name" OtherKey="empoyee_name" Type="employee_sale" />
      <Association Name="employee_employee_timecode" Member="employee_timecodes" ThisKey="name" OtherKey="employee_name" Type="employee_timecode" />
    </Type>
  </Table>
  <Table Name="dbo.employee_hour" Member="employee_hours">
    <Type Name="employee_hour">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employee_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="client_name" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ot" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="client_employee_hour" Member="client" ThisKey="client_name" OtherKey="name" Type="client" IsForeignKey="true" />
      <Association Name="employee_employee_hour" Member="employee" ThisKey="employee_name" OtherKey="name" Type="employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.employee_member" Member="employee_members">
    <Type Name="employee_member">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employee_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="member_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ot" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="employee_employee_member" Member="employee" ThisKey="employee_name" OtherKey="name" Type="employee" IsForeignKey="true" />
      <Association Name="member_employee_member" Member="member" ThisKey="member_name" OtherKey="name" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.employee_sale" Member="employee_sales">
    <Type Name="employee_sale">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="item_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="qnt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="empoyee_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ot" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="employee_employee_sale" Member="employee" ThisKey="empoyee_name" OtherKey="name" Type="employee" IsForeignKey="true" />
      <Association Name="item_employee_sale" Member="item" ThisKey="item_id" OtherKey="id" Type="item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.employee_timecode" Member="employee_timecodes">
    <Type Name="employee_timecode">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employee_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="timecode_code" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ot" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="employee_employee_timecode" Member="employee" ThisKey="employee_name" OtherKey="name" Type="employee" IsForeignKey="true" />
      <Association Name="timecode_employee_timecode" Member="timecode" ThisKey="timecode_code" OtherKey="code" Type="timecode" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.groups" Member="groups">
    <Type Name="group">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="timecodeprice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="memberprice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hourprice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="timecode" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="member" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="hour" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="prepairhour" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="minprice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="vip" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="group_client" Member="clients" ThisKey="id" OtherKey="group_id" Type="client" />
    </Type>
  </Table>
  <Table Name="dbo.hourtemplate" Member="hourtemplates">
    <Type Name="hourtemplate">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="minute" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="beghour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="endhour" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="hourtemplate_client" Member="clients" ThisKey="id" OtherKey="ht" Type="client" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="category_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="item_employee_sale" Member="employee_sales" ThisKey="id" OtherKey="item_id" Type="employee_sale" />
      <Association Name="category_item" Member="category" ThisKey="category_id" OtherKey="id" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.member" Member="members">
    <Type Name="member">
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="money" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ot" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Association Name="member_client" Member="clients" ThisKey="name" OtherKey="member_name" Type="client" />
      <Association Name="member_employee_member" Member="employee_members" ThisKey="name" OtherKey="member_name" Type="employee_member" />
    </Type>
  </Table>
  <Table Name="dbo.reserve" Member="reserves">
    <Type Name="reserve">
      <Column Name="id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="client_name" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ot" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="steamid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="client_reserve" Member="client" ThisKey="client_name" OtherKey="name" Type="client" IsForeignKey="true" />
    </Type>
  </Table>
</Database>